### ISSUE TITLE
No features work!

### ISSUE THREAD

**Issue by amanjitsk** [lgeiger/ide-python#22] opened 2017-09-27 22:42 UTC
I have tried using Atom 1.21.0-beta2, but `ide-python` does not work. What I mean by this is that none of the features such as autocompletion, outline view work. Infact, when I install `ide-python`, my regular autocomplete (from the `autocomplete-python` package) also stops working. Do you think you know what the problem could be?

**Comment by lgeiger** [comment] 2017-09-27 22:54
Have you installed `pyls` and verified it works?
See: https://github.com/lgeiger/ide-python#installation

**Comment by lgeiger** [comment] 2017-09-27 22:55
You also need the `atom-ide-ui` package to make it work.

**Comment by amanjitsk** [comment] 2017-09-28 02:36
Yea I have the `atom-ide-ui` package and have also installed `pyls` for `python3`. Does the version of python make a difference? Because I want to use it for `python3`. Infact, I have even done the same setup for Atom stable version `1.20.1` but makes no difference!

**Comment by dpwrussell** [comment] 2017-09-28 20:36
This is happening to me sporadically. Sometimes it is working and then all of the IDE functionality stops. So far it has only happened to me in python, but I have mainly been working in Python recently. All autocomplete stops (I'm guessing because it is hung, waiting for input from the ide) and any linting messages get stuck when I have long ago fixed the issue. Usually this does not resolve until Atom is restarted.

An example of the stuck linting. the undefined name has been deleted, but the error remains. This 100% overlaps with all other functionality ceasing.

![py-ide](https://user-images.githubusercontent.com/1889043/30989225-f869fd02-a46a-11e7-9875-363c1f26ec64.png)

I tried opening the console to see if there were error messages, but there were none.

**Comment by lgeiger** [comment] 2017-09-28 21:35
What operating system are you on @dpwrussell, @amanjitsk

**Comment by amanjitsk** [comment] 2017-09-28 21:55
@lgeiger MacOS

**Comment by dpwrussell** [comment] 2017-09-28 23:43
Also MacOS.

**Comment by culhatsker** [comment] 2017-10-05 16:53
Hello @amanjitsk,
There's an issue with similar symptoms:
https://github.com/lgeiger/ide-python/issues/20
Can you please check if you have the same problem?

**Comment by lgeiger** [comment] 2017-10-20 20:12
Is this issue still reproducible with the latest version of `ide-python`?

**Comment by amanjitsk** [comment] 2017-10-20 20:29
Not that I can see, it somehow worked after some time. I have no clue how, but it works good now! However, when this package is used together with `autocomplete-python`, the autocomplete formatting gets messed up, I have to disable this package's autocomplete by disabling `jedi-enable` in order to get the correct formatting back. Also, occasionally the package hangs, but all-in-all its pretty good. Thanks for the great work!

**Comment by lgeiger** [comment] 2017-10-20 20:34
> Not that I can see, it somehow worked after some time.

Glad it's working 👍 
I'm going to close this issue, feel free to reopen if the issue is appearing again.

> However, when this package is used together with `autocomplete-python`, the autocomplete formatting gets messed up, I have to disable this package's autocomplete by disabling `jedi-enable` in order to get the correct formatting back.

Unfortunately that's somehow expected. Using multiple providers for the same language doesn't work very well in `autocomplete-plus`. Disabling either `autocomplete-python` or the jedi plugin should fix it.

**Closed by lgeiger** 2017-10-20 20:34 UTC
Labels: bug

**Comment by cocoa1231** [comment] 2020-03-30 10:07
Hello

This issue seems to be happening with me on Linux Mint 19.3
It was working properly yesterday, today I came and none of the features seem to be working. I've got a fresh installation of Linux Mint and Atom, with just atom-ide-ui, ide-python and script packages installed and the language server as well. I can't even find any debugging information, could you help me with this?

**Comment by TianshuangQiu** [comment] 2021-01-24 20:48
I have the same issue today. I tried replacing Atom-ide-ui with linter-ui and it doesn't work.

**Comment by danieltroger** [comment] 2021-01-28 11:16
Hello, I have this issue too on macOS with atom 1.54.0. These are my installed packages:
```
Built-in Atom Packages (93)
├── atom-dark-syntax@0.29.1
├── atom-dark-ui@0.53.3
├── atom-light-syntax@0.29.1
├── atom-light-ui@0.46.3
├── base16-tomorrow-dark-theme@1.6.0
├── base16-tomorrow-light-theme@1.6.0
├── one-dark-ui@1.12.5
├── one-light-ui@1.12.5
├── one-dark-syntax@1.8.4
├── one-light-syntax@1.8.4
├── solarized-dark-syntax@1.3.0
├── solarized-light-syntax@1.3.0
├── about@1.9.1
├── archive-view@0.65.2
├── autocomplete-atom-api@0.10.7
├── autocomplete-css@0.17.5
├── autocomplete-html@0.8.8
├── autocomplete-plus@2.42.3
├── autocomplete-snippets@1.12.1
├── autoflow@0.29.4
├── autosave@0.24.6
├── background-tips@0.28.0
├── bookmarks@0.46.0
├── bracket-matcher@0.91.2
├── command-palette@0.43.5
├── dalek@0.2.2
├── deprecation-cop@0.56.9
├── dev-live-reload@0.48.1
├── encoding-selector@0.23.9
├── exception-reporting@0.43.1
├── find-and-replace@0.219.7
├── fuzzy-finder@1.14.3
├── github@0.36.2
├── git-diff@1.3.9
├── go-to-line@0.33.0
├── grammar-selector@0.50.1
├── image-view@0.64.0
├── incompatible-packages@0.27.3
├── keybinding-resolver@0.39.0
├── line-ending-selector@0.7.7
├── link@0.31.6
├── markdown-preview@0.160.2
├── metrics@1.8.1
├── notifications@0.71.0
├── open-on-github@1.3.2
├── package-generator@1.3.0
├── settings-view@0.261.6
├── snippets@1.5.1
├── spell-check@0.76.2
├── status-bar@1.8.17
├── styleguide@0.49.12
├── symbols-view@0.118.4
├── tabs@0.110.0
├── timecop@0.36.2
├── tree-view@0.228.2
├── update-package-dependencies@0.13.1
├── welcome@0.36.9
├── whitespace@0.37.7
├── wrap-guide@0.41.0
├── language-c@0.60.19
├── language-clojure@0.22.8
├── language-coffee-script@0.50.0
├── language-csharp@1.1.0
├── language-css@0.44.4
├── language-gfm@0.90.8
├── language-git@0.19.1
├── language-go@0.47.2
├── language-html@0.53.1
├── language-hyperlink@0.17.1
├── language-java@0.32.0
├── language-javascript@0.134.1
├── language-json@1.0.5
├── language-less@0.34.3
├── language-make@0.23.0
├── language-mustache@0.14.5
├── language-objective-c@0.16.0
├── language-perl@0.38.1
├── language-php@0.44.7
├── language-property-list@0.9.1
├── language-python@0.53.5
├── language-ruby@0.72.23
├── language-ruby-on-rails@0.25.3
├── language-rust-bundled@0.1.0
├── language-sass@0.62.1
├── language-shellscript@0.28.2
├── language-source@0.9.0
├── language-sql@0.25.10
├── language-text@0.7.4
├── language-todo@0.29.4
├── language-toml@0.20.0
├── language-typescript@0.6.3
├── language-xml@0.35.3
└── language-yaml@0.32.0

Community Packages (17) /Users/daniel/.atom/packages
├── atom-beautify@0.33.4
├── atom-ide-base@2.1.1
├── atom-ide-definitions@0.4.0
├── atom-ide-hyperclick@1.0.9
├── atom-ide-javascript@1.5.0
├── atom-typescript@14.1.2
├── autocomplete-paths@2.12.17
├── busy-signal@2.0.1
├── ide-python@1.7.2
├── intentions@1.1.5
├── javascript-drag-import@0.1.13
├── language-vue@0.26.0
├── linter@3.3.0
├── linter-eslint@8.5.5
├── linter-ui-default@2.4.1
├── markdown-preview-enhanced@0.18.8
└── minimap@4.39.5
```

**Comment by aminya** [comment] 2021-01-28 12:42
Please update atom-ide-base.

**Comment by danieltroger** [comment] 2021-01-28 17:56
@aminya thanks. I did that and a "outline" dialog popped up on the right hand side after two restarts. It still didn't work. I then went into a directory containing python code and ran `atom . ` and then it started working! Which was incredible. But a bit hard to figure out and unexpected, as it didn't say anywhere "you have to open the directory of your code as project folder".

**Comment by j4sgf** [comment] 2021-06-11 02:11
@danieltroger solutions works for me. All I need to do is just ran **atom .**

**Comment by Shimoon** [comment] 2022-01-31 15:23
Hello!
I have the same issue on windows 10.
I have a fresh installation with `pyls` for `python3` and also `atom-ide-ui` installed.
I tried to run `atom .` it partially resolve the issue but some of the ide packages randomly won't show/works and it appears that only the linter package detect errors and warnings no matter what (I get a conflict between the atom-ide-diagnostics and the linter package too).
