### ISSUE TITLE
python language server eats all memory

### ISSUE THREAD

**Issue by tofuhead** [lgeiger/ide-python#144] opened 2018-11-27 20:15 UTC
After working couple of minutes I see python language server eating all my memory,
and computer starts lagging because it's swapping memory.
Manually killing the language server memory is freed, but it doesn't take long for it to start piling up again. 

using latest version on Atom, and Python-Ide. On Linux Kubuntu 18.10.

**Comment by HetorusNL** [comment] 2018-11-30 10:00
I'm experiencing the same issue, also on latest version of Atom and ide-python, but I am however using python3 instead of the default python.

Some, maybe related, errors get logged in /var/log/syslog about code-highlight:
```
Nov 30 10:26:03 Machine-name atom.desktop[1474]: #033[31m[2018-11-30 10:26:03.493] [ERROR] code-highlight - #033[39mError getting code highlights { TypeError: Cannot read property 'map' of null
Nov 30 10:26:03 Machine-name atom.desktop[1474]:     at Function.<anonymous> (/home/hetorusnl/.atom/packages/ide-python/node_modules/atom-languageclient/build/lib/adapters/code-highlight-adapter.js:32:31)
Nov 30 10:26:03 Machine-name atom.desktop[1474]:     at Generator.next (<anonymous>)
Nov 30 10:26:03 Machine-name atom.desktop[1474]:     at fulfilled (/home/hetorusnl/.atom/packages/ide-python/node_modules/atom-languageclient/build/lib/adapters/code-highlight-adapter.js:4:58)
Nov 30 10:26:03 Machine-name atom.desktop[1474]:     at <anonymous>
Nov 30 10:26:03 Machine-name atom.desktop[1474]:   rawStack: [ CallSite {}, CallSite {}, CallSite {}, CallSite {} ] }
Nov 30 10:26:11 Machine-name atom.desktop[1474]: #033[31m[2018-11-30 10:26:11.153] [ERROR] code-highlight - #033[39mError getting code highlights { TypeError: Cannot read property 'map' of null
Nov 30 10:26:11 Machine-name atom.desktop[1474]:     at Function.<anonymous> (/home/hetorusnl/.atom/packages/ide-python/node_modules/atom-languageclient/build/lib/adapters/code-highlight-adapter.js:32:31)
Nov 30 10:26:11 Machine-name atom.desktop[1474]:     at Generator.next (<anonymous>)
Nov 30 10:26:11 Machine-name atom.desktop[1474]:     at fulfilled (/home/hetorusnl/.atom/packages/ide-python/node_modules/atom-languageclient/build/lib/adapters/code-highlight-adapter.js:4:58)
Nov 30 10:26:11 Machine-name atom.desktop[1474]:     at <anonymous>
Nov 30 10:26:11 Machine-name atom.desktop[1474]:   rawStack: [ CallSite {}, CallSite {}, CallSite {}, CallSite {} ] }
```

And after a while of use, a lot of jedi processes get spawned (haven't used atom much this session yet, so now there are only a few processes), see attached screenshot:
![screenshot from 2018-11-30 10-58-14](https://user-images.githubusercontent.com/17402329/49282211-e2a81600-f48e-11e8-96ef-5d7270d5899a.png)

**Comment by thedrow** [comment] 2018-12-31 13:30
This should be fixed with the new jedi release.
Can we close this?

**Comment by HetorusNL** [comment] 2019-01-02 19:10
is there something to be done to (force?) the newest jedi version to be installed/used, or should it happen automagically?

**Comment by HetorusNL** [comment] 2019-01-03 00:53
thanks for the quick reply, i'll try it tomorrow.

**Comment by HetorusNL** [comment] 2019-01-03 08:32
only upgrading the python-language-server caused jedi to remain (at version jedi==13.1), installing --upgrading jedi installed the version that fixed the bug (according to the changelog of jedi, jedi==13.2).
since ide-python requires jedi>=0.12, it wasn't upgraded with the python-language-server.
so i assume that the problem is solved with this

**Closed** 2019-01-03 11:07 UTC
