### ISSUE TITLE
Uncaught Error: Header must provide a Content-Length property.

### ISSUE THREAD

**Issue by djpremier** [lgeiger/ide-python#117] opened 2018-06-06 17:34 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Debian GNU/Linux
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 0.10.0

### Stack Trace

Uncaught Error: Header must provide a Content-Length property.

```
At /home/djpremier/.atom/packages/ide-python/node_modules/vscode-jsonrpc/lib/messageReader.js:200

Error: Header must provide a Content-Length property.
    at StreamMessageReader.onData (/packages/ide-python/node_modules/vscode-jsonrpc/lib/messageReader.js:200:27)
    at /packages/ide-python/node_modules/vscode-jsonrpc/lib/messageReader.js:185:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

### Commands

```
     -2:21.5.0 core:undo (input.hidden-input)
  5x -2:05.7.0 core:backspace (input.hidden-input)
     -1:51.8.0 core:move-right (input.hidden-input)
     -1:51.4.0 core:delete (input.hidden-input)
     -1:51.1.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -1:50.5.0 core:move-left (input.hidden-input)
     -1:50.2.0 core:backspace (input.hidden-input)
     -1:49.4.0 core:delete (input.hidden-input)
     -1:47.5.0 core:backspace (input.hidden-input)
     -1:42 core:save (input.hidden-input)
     -1:06.6.0 markdown-writer:insert-new-line (input.hidden-input)
     -1:06.6.0 editor:newline (input.hidden-input)
     -1:04.4.0 core:save (input.hidden-input)
     -0:59.5.0 editor:select-to-first-character-of-line (input.hidden-input)
  4x -0:54 core:backspace (input.hidden-input)
     -0:48.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-bootstrap4 1.4.0 
atom-clock 0.1.16 
atom-ide-debugger-python 0.7.1 
atom-ide-ui 0.12.0 
atom-live-server 2.2.0 
atom-runner 2.7.1 
autocomplete-python 1.10.5 
chrome-color-picker 0.8.0 
dragon-fire-syntax 0.5.3 
file-header 1.13.9 
file-icons 2.1.21 
flex-tool-bar 2.1.0 
hey-pane 1.1.0 
ide-python 0.10.0 
kite 0.93.0 
markdown-writer 2.7.3 
minimap 4.29.8 
minimap-pigments 0.2.2 
open-in-browser 0.5.2 
pigments 0.40.2 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.8.1 
preview-inline 1.5.1 
python-debugger 0.2.0 
python-indent 1.1.5 
script 3.18.1 
sync-settings 0.8.6 
teletype 0.13.3 
tool-bar 1.1.7 
tool-bar-atom 1.7.0 
tool-bar-gui 2.0.2 
tool-bar-main 0.0.11 
tool-bar-markdown-writer 0.3.1 
tool-bar-shortcuts 0.1.5 
toolbar-iconshortcuts 3.17.0 
```

**Comment by lgeiger** [comment] 2018-06-07 10:15
Closing as duplicate of #106

**Closed by lgeiger** 2018-06-07 10:15 UTC

**Comment by matg19** [comment] 2020-02-16 23:50
This error just showed up out of nothing. I keep seeing it despite having uninstalled ide-python to stop seeing the error message...

The error shows up as coming from a file that no longer exists because ide-python is no longer in my system...

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home
**Thrown From**: 'ide-python' package vundefined


### Stack Trace

Uncaught Error: Header must provide a Content-Length property.

```
At C:\Users\MG\.atom\packages\ide-python\node_modules\vscode-languageserver-protocol\node_modules\vscode-jsonrpc\lib\messageReader.js:200

Error: Header must provide a Content-Length property.
    at SocketMessageReader.StreamMessageReader.onData (/packages/ide-python/node_modules/vscode-languageserver-protocol/node_modules/vscode-jsonrpc/lib/messageReader.js:200:27)
    at /packages/ide-python/node_modules/vscode-languageserver-protocol/node_modules/vscode-jsonrpc/lib/messageReader.js:185:19)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

### Commands

```
  2x -8:12.7.0 core:backspace (input.hidden-input)
     -8:09.0 hydrogen:run (input.hidden-input)
     -8:09.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.has-selection)
     -7:56.6.0 hydrogen:run (input.hidden-input)
     -7:56.6.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.has-selection)
     -7:33.4.0 hydrogen:run (input.hidden-input)
     -7:33.4.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.has-selection)
     -7:28.4.0 hydrogen:run (input.hidden-input)
     -7:28.4.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.has-selection)
  4x -7:16.7.0 core:backspace (input.hidden-input)
     -2:34.7.0 hydrogen:run (input.hidden-input)
     -2:34.7.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.has-selection)
     -2:10.3.0 hydrogen:run (input.hidden-input)
     -2:10.3.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.has-selection)
     -2:07.0 hydrogen:run (input.hidden-input)
     -2:07.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.has-selection)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-ide-ui 0.13.0 
atom-latex 0.9.1 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-visual-studio-code-light-ui 2.1.0 
atom-visual-studio-code-ui 1.3.4 
atomic-emacs 0.15.0 
autocomplete-paths 2.12.2 
autocomplete-python 1.16.0 
autocomplete-R 0.6.0 
daverona-laravel-syntax 0.0.1 
daverona-mellow-syntax 0.0.1 
dicy 0.1.2 
ghar-dark-syntax 2.0.0 
GobbieGobGoo 1.0.4 
handsome-light-syntax 0.3.4 
Hydrogen 2.14.0 
hydrogen-launcher 1.2.2 
ide-r 0.1.8 
language-knitr 0.4.0 
language-latex 1.2.0 
language-r 0.4.2 
latex 0.50.2 
latexer 0.3.0 
midnight-owl-syntax 0.1.0 
monokai 0.24.0 
moonlight 0.11.0 
now-syntax 0.3.0 
nucleus-dark-ui 0.12.3 
pdf-view 0.72.0 
platformio-ide-terminal 2.10.0 
rbox 0.5.0 
rzx-dark-syntax 1.1.1 
seti-syntax 1.2.0 
seti-ui 1.11.0 
summer-night-syntax 2.0.1 
visual-studio-dark-syntax 0.2.0 
```
